openapi: 3.0.0
info:
  title: Api DOCS Soul Todo Service - OpenAPI 3.0
  description: soul parking todo api
  contact:
    email: alfiankan19@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
  - url: http://localhost:5000
tags:
  - name: todo
paths:
  /todo/{todo_id}:
    get:
      tags:
        - todo
      summary: get todos
      operationId: getTodos
      parameters:
        - name: todo_id
          in: path
          description: todo id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
    put:
      tags:
        - todo
      summary: Update todo
      operationId: updateTodo
      parameters:
        - name: todo_id
          in: path
          description: todo id
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
    delete:
      tags:
        - todo
      summary: Deletes todo
      operationId: deleteTodo
      parameters:
        - name: todo_id
          in: path
          description: todo id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
  /todo:
    post:
      tags:
        - todo
      summary: Add a new todo
      operationId: addTodo
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

    get:
      tags:
        - todo
      summary: get todos
      operationId: getTodo
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

  /todo/{todo_id}/finish:
    patch:
      tags:
        - todo
      summary: finish todos
      operationId: finishTodo
      parameters:
        - name: todo_id
          in: path
          description: todo id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object

